sut:
  image: node:4
  command: sh -c 'npm install && npm test'
  volumes:
    - .:/app
  environment:
    - CI=true
  links:
    - ravend
    - ravend-ssl
    - ravend-username-only
  working_dir: /app

ravend:
  image: msftserver/ravencoin-core:0.15.0.1-alpine
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -rpcport=18767
    -rpcuser=foo
    -server
  ports:
    - 18767:18767

ravend-ssl:
  image: MSFTserver/ravencoin-core:0.11-alpine
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -rpcport=18768
    -rpcssl
    -rpcsslcertificatechainfile=/etc/ssl/ravend/cert.pem
    -rpcsslprivatekeyfile=/etc/ssl/ravend/key.pem
    -rpcuser=foo
    -server
  volumes:
    - ./test/config/ssl:/etc/ssl/ravend
  ports:
    - 18768:18768

ravend-username-only:
  image: MSFTserver/ravencoin-core:0.11-alpine
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcport=18769
    -rpcuser=foo
    -server
  ports:
    - 18769:18769
